version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cfc-webhook-degrosser"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1mv8ngeobrljz"
s3_prefix = "cfc-webhook-degrosser"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DegrosserFormSpreeAllowedData=\"DegrosserFormSpreeAllowedData\""
